/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#ffecea",
        "on-secondary-container": "#636262",
        "surface-container": "#eeeeee",
        "primary-fixed": "#ffdad6",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#410002",
        "secondary": "#5f5e5e",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#191c1d",
        "primary-container": "#d71921",
        "on-surface-variant": "#5d3f3c",
        "tertiary-container": "#6b6d6e",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed-variant": "#474746",
        "inverse-primary": "#ffb4ac",
        "tertiary-fixed": "#e1e3e4",
        "surface-container-low": "#f3f3f4",
        "inverse-on-surface": "#f0f1f1",
        "on-tertiary-fixed-variant": "#454748",
        "surface-dim": "#dadada",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-tertiary-container": "#eff0f1",
        "surface-tint": "#c00015",
        "inverse-surface": "#2f3131",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed-variant": "#93000e",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "on-surface": "#1a1c1c",
        "primary": "#ae0012",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#ffb4ac",
        "on-tertiary": "#ffffff",
        "outline-variant": "#e6bdb8",
        "tertiary": "#525556",
        "surface": "#f9f9f9",
        "background": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#e2dfde",
        "error": "#ba1a1a",
        "outline": "#916f6b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "20px",
        "max-width": "1280px",
        "margin-desktop": "40px",
        "base": "8px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
      animation: {
        marquee: 'marquee 120s linear infinite',
      },
    },
  },
  plugins: [],
};
